---

- block:

  - name: Logstash APT repo key
    apt_key:
      state: present
      url: "{{logstash_gpg_key}}"

  - name: Logstash Repository (Debian)
    apt_repository:
      state: present
      repo: "deb {{logstash_apt_repository}} stable main"
      update_cache: yes
        
  - name: Logstash packages (Debian)
    apt:
      state: "{{ (logstash_upgrade) | ternary('latest', 'present') }}"
      name: "{{logstash_package}}"

  when: logstash_use_repo

- block:

  - name: Download logstash DEB
    get_url:
      url: "{{logstash_package_url}}"
      dest: "/var/cache/apt/archives/logstash-{{logstash_version}}.deb"

  - name: Install logstash from DEB
    apt:
      deb: "/var/cache/apt/archives/logstash-{{logstash_version}}.deb"
      state: present
    notify: logstash restart

# vi:ts=2:sw=2:et:ft=yaml
